# Theme Settings
# theme: jekyll-theme-leap-day
# remote_theme             : "pages-themes/leap-day"
# leap_day_skin    : "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# remote_theme             : "mmistakes/minimal-mistakes"
# minimal_mistakes_skin    : "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

theme: jekyll-theme-leap-day

# Site Settings
title                    :  Blog
title_separator          : "|"
SEOTitle                 : "Stella Zhao | BY Blog"
description              : "Professional Portfolio"
url                      : "https://zephyr1022.github.io/"
header-img               :  /assets/image/icons/YObP083yQMSvrkHpDcOWmw_thumb_72dc.jpg
baseurl: ""               # for example, '/blog' if your blog hosted on 'host/blog'
keyword                  : "BY, BY Blog, Zephyer1022, Stella, Data"


# title: Xingmeng "Stella" Zhao
# zip_url: http://example.com/download.zip
# another_url: another value

# Sidebar settings
sidebar: true                           # 是否开启侧边栏
sidebar-about-description: "Blablabla"
sidebar-avatar: /assets/images/icons/isss_tile.png

# SNS settings
# RSS: false
# weibo_username:     username
# zhihu_username:     username
# github_username:    username
# facebook_username:  username


# Analytics settings
# Baidu Analytics
# ba_track_id: 83e259f69b37d02a4633a2b7d960139c

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto

# Site Author
# author:
  #name             : "Stella Zhao"
  #avatar           : "/assets/images/icons/isss_tile.png"
  #bio              : "Data Analyst"
  #location         : "Denver, Colorado"


# This tells Jekyll to look in the _scss directory for your Sass/SCSS partials. Because of this, you'll also need to shorten your import statement to: @import 'stylesheet';
sass:
    sass_dir: ./_scss
    
